# Generated by Django 2.2.1 on 2019-05-24 13:53

from django.db import migrations


def create_flag(apps, schema_editor):
    Flag = apps.get_model('flags', 'Flag')
    Flag.objects.create(name='show_ratings', is_active=False)


def delete_flag(apps, schema_editor):
    Flag = apps.get_model('flags', 'Flag')
    Flag.objects.filter(name='show_ratings').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_flag, reverse_code=delete_flag)
    ]
